<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profile/profile.proto

namespace GPBMetadata\Profile;

class Profile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x84\x08\x0A\x15profile/profile.proto\x12\x07profile\"\$\x0A\x11GetProfileRequest\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x09\"s\x0A\x07Profile\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0F\x0A\x07user_id\x18\x02 \x01(\x09\x12\x10\x0A\x08fullname\x18\x03 \x01(\x09\x12\x11\x0A\x09photo_url\x18\x04 \x01(\x09\x12\x12\x0A\x0Acreated_at\x18\x05 \x01(\x09\x12\x12\x0A\x0Aupdated_at\x18\x06 \x01(\x09\"9\x0A\x14CreateProfileRequest\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x09\x12\x10\x0A\x08fullname\x18\x02 \x01(\x09\"9\x0A\x14UpdateProfileRequest\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x09\x12\x10\x0A\x08fullname\x18\x02 \x01(\x09\"B\x0A\x19UploadProfilePhotoRequest\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x09\x12\x14\x0A\x0Cbase64_image\x18\x02 \x01(\x09\"Q\x0A\x1AUploadProfilePhotoResponse\x12\x0F\x0A\x07success\x18\x01 \x01(\x08\x12\x11\x0A\x09photo_url\x18\x02 \x01(\x09\x12\x0F\x0A\x07message\x18\x03 \x01(\x09\",\x0A\x19DeleteProfilePhotoRequest\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x09\">\x0A\x1ADeleteProfilePhotoResponse\x12\x0F\x0A\x07success\x18\x01 \x01(\x08\x12\x0F\x0A\x07message\x18\x02 \x01(\x092\x8E\x03\x0A\x0EProfileService\x12:\x0A\x0AGetProfile\x12\x1A.profile.GetProfileRequest\x1A\x10.profile.Profile\x12@\x0A\x0DCreateProfile\x12\x1D.profile.CreateProfileRequest\x1A\x10.profile.Profile\x12@\x0A\x0DUpdateProfile\x12\x1D.profile.UpdateProfileRequest\x1A\x10.profile.Profile\x12]\x0A\x12UploadProfilePhoto\x12\".profile.UploadProfilePhotoRequest\x1A#.profile.UploadProfilePhotoResponse\x12]\x0A\x12DeleteProfilePhoto\x12\".profile.DeleteProfilePhotoRequest\x1A#.profile.DeleteProfilePhotoResponseB3Z1github.com/MuhammadMiftaa/Refina-Protobuf/profileb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

