<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profile/profile.proto

namespace Profile;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>profile.UploadProfilePhotoRequest</code>
 */
class UploadProfilePhotoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * Base64 encoded image data
     *
     * Generated from protobuf field <code>string base64_image = 2;</code>
     */
    protected $base64_image = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type string $base64_image
     *           Base64 encoded image data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Profile\Profile::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Base64 encoded image data
     *
     * Generated from protobuf field <code>string base64_image = 2;</code>
     * @return string
     */
    public function getBase64Image()
    {
        return $this->base64_image;
    }

    /**
     * Base64 encoded image data
     *
     * Generated from protobuf field <code>string base64_image = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBase64Image($var)
    {
        GPBUtil::checkString($var, True);
        $this->base64_image = $var;

        return $this;
    }

}

