<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/transaction.proto

namespace Transaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transaction.Budget</code>
 */
class Budget extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     */
    protected $user_id = '';
    /**
     * "overall" or "category"
     *
     * Generated from protobuf field <code>string scope = 3;</code>
     */
    protected $scope = '';
    /**
     * nullable, only for category scope
     *
     * Generated from protobuf field <code>string category_id = 4;</code>
     */
    protected $category_id = '';
    /**
     * populated from join
     *
     * Generated from protobuf field <code>string category_name = 5;</code>
     */
    protected $category_name = '';
    /**
     * "all" or wallet_id
     *
     * Generated from protobuf field <code>string wallet_scope = 6;</code>
     */
    protected $wallet_scope = '';
    /**
     * nullable
     *
     * Generated from protobuf field <code>string wallet_id = 7;</code>
     */
    protected $wallet_id = '';
    /**
     * populated from external service
     *
     * Generated from protobuf field <code>string wallet_name = 8;</code>
     */
    protected $wallet_name = '';
    /**
     * Generated from protobuf field <code>double monthly_limit = 9;</code>
     */
    protected $monthly_limit = 0.0;
    /**
     * calculated from transactions
     *
     * Generated from protobuf field <code>double current_spent = 10;</code>
     */
    protected $current_spent = 0.0;
    /**
     * format: "YYYY-MM"
     *
     * Generated from protobuf field <code>string period = 11;</code>
     */
    protected $period = '';
    /**
     * Generated from protobuf field <code>int32 streak_count = 12;</code>
     */
    protected $streak_count = 0;
    /**
     * Generated from protobuf field <code>bool streak_active = 13;</code>
     */
    protected $streak_active = false;
    /**
     * Generated from protobuf field <code>string created_at = 14;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 15;</code>
     */
    protected $updated_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $user_id
     *     @type string $scope
     *           "overall" or "category"
     *     @type string $category_id
     *           nullable, only for category scope
     *     @type string $category_name
     *           populated from join
     *     @type string $wallet_scope
     *           "all" or wallet_id
     *     @type string $wallet_id
     *           nullable
     *     @type string $wallet_name
     *           populated from external service
     *     @type float $monthly_limit
     *     @type float $current_spent
     *           calculated from transactions
     *     @type string $period
     *           format: "YYYY-MM"
     *     @type int $streak_count
     *     @type bool $streak_active
     *     @type string $created_at
     *     @type string $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * "overall" or "category"
     *
     * Generated from protobuf field <code>string scope = 3;</code>
     * @return string
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * "overall" or "category"
     *
     * Generated from protobuf field <code>string scope = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope = $var;

        return $this;
    }

    /**
     * nullable, only for category scope
     *
     * Generated from protobuf field <code>string category_id = 4;</code>
     * @return string
     */
    public function getCategoryId()
    {
        return $this->category_id;
    }

    /**
     * nullable, only for category scope
     *
     * Generated from protobuf field <code>string category_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_id = $var;

        return $this;
    }

    /**
     * populated from join
     *
     * Generated from protobuf field <code>string category_name = 5;</code>
     * @return string
     */
    public function getCategoryName()
    {
        return $this->category_name;
    }

    /**
     * populated from join
     *
     * Generated from protobuf field <code>string category_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryName($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_name = $var;

        return $this;
    }

    /**
     * "all" or wallet_id
     *
     * Generated from protobuf field <code>string wallet_scope = 6;</code>
     * @return string
     */
    public function getWalletScope()
    {
        return $this->wallet_scope;
    }

    /**
     * "all" or wallet_id
     *
     * Generated from protobuf field <code>string wallet_scope = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletScope($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_scope = $var;

        return $this;
    }

    /**
     * nullable
     *
     * Generated from protobuf field <code>string wallet_id = 7;</code>
     * @return string
     */
    public function getWalletId()
    {
        return $this->wallet_id;
    }

    /**
     * nullable
     *
     * Generated from protobuf field <code>string wallet_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_id = $var;

        return $this;
    }

    /**
     * populated from external service
     *
     * Generated from protobuf field <code>string wallet_name = 8;</code>
     * @return string
     */
    public function getWalletName()
    {
        return $this->wallet_name;
    }

    /**
     * populated from external service
     *
     * Generated from protobuf field <code>string wallet_name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletName($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double monthly_limit = 9;</code>
     * @return float
     */
    public function getMonthlyLimit()
    {
        return $this->monthly_limit;
    }

    /**
     * Generated from protobuf field <code>double monthly_limit = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setMonthlyLimit($var)
    {
        GPBUtil::checkDouble($var);
        $this->monthly_limit = $var;

        return $this;
    }

    /**
     * calculated from transactions
     *
     * Generated from protobuf field <code>double current_spent = 10;</code>
     * @return float
     */
    public function getCurrentSpent()
    {
        return $this->current_spent;
    }

    /**
     * calculated from transactions
     *
     * Generated from protobuf field <code>double current_spent = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setCurrentSpent($var)
    {
        GPBUtil::checkDouble($var);
        $this->current_spent = $var;

        return $this;
    }

    /**
     * format: "YYYY-MM"
     *
     * Generated from protobuf field <code>string period = 11;</code>
     * @return string
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * format: "YYYY-MM"
     *
     * Generated from protobuf field <code>string period = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setPeriod($var)
    {
        GPBUtil::checkString($var, True);
        $this->period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 streak_count = 12;</code>
     * @return int
     */
    public function getStreakCount()
    {
        return $this->streak_count;
    }

    /**
     * Generated from protobuf field <code>int32 streak_count = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setStreakCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->streak_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool streak_active = 13;</code>
     * @return bool
     */
    public function getStreakActive()
    {
        return $this->streak_active;
    }

    /**
     * Generated from protobuf field <code>bool streak_active = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setStreakActive($var)
    {
        GPBUtil::checkBool($var);
        $this->streak_active = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 14;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 15;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

}

