<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/transaction.proto

namespace Transaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transaction.CreateBudgetRequest</code>
 */
class CreateBudgetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * "overall" or "category"
     *
     * Generated from protobuf field <code>string scope = 1;</code>
     */
    protected $scope = '';
    /**
     * optional, required if scope = "category"
     *
     * Generated from protobuf field <code>string category_id = 2;</code>
     */
    protected $category_id = '';
    /**
     * optional, null = all wallets
     *
     * Generated from protobuf field <code>string wallet_id = 3;</code>
     */
    protected $wallet_id = '';
    /**
     * Generated from protobuf field <code>double monthly_limit = 4;</code>
     */
    protected $monthly_limit = 0.0;
    /**
     * format: "YYYY-MM"
     *
     * Generated from protobuf field <code>string period = 5;</code>
     */
    protected $period = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $scope
     *           "overall" or "category"
     *     @type string $category_id
     *           optional, required if scope = "category"
     *     @type string $wallet_id
     *           optional, null = all wallets
     *     @type float $monthly_limit
     *     @type string $period
     *           format: "YYYY-MM"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * "overall" or "category"
     *
     * Generated from protobuf field <code>string scope = 1;</code>
     * @return string
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * "overall" or "category"
     *
     * Generated from protobuf field <code>string scope = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope = $var;

        return $this;
    }

    /**
     * optional, required if scope = "category"
     *
     * Generated from protobuf field <code>string category_id = 2;</code>
     * @return string
     */
    public function getCategoryId()
    {
        return $this->category_id;
    }

    /**
     * optional, required if scope = "category"
     *
     * Generated from protobuf field <code>string category_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_id = $var;

        return $this;
    }

    /**
     * optional, null = all wallets
     *
     * Generated from protobuf field <code>string wallet_id = 3;</code>
     * @return string
     */
    public function getWalletId()
    {
        return $this->wallet_id;
    }

    /**
     * optional, null = all wallets
     *
     * Generated from protobuf field <code>string wallet_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double monthly_limit = 4;</code>
     * @return float
     */
    public function getMonthlyLimit()
    {
        return $this->monthly_limit;
    }

    /**
     * Generated from protobuf field <code>double monthly_limit = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setMonthlyLimit($var)
    {
        GPBUtil::checkDouble($var);
        $this->monthly_limit = $var;

        return $this;
    }

    /**
     * format: "YYYY-MM"
     *
     * Generated from protobuf field <code>string period = 5;</code>
     * @return string
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * format: "YYYY-MM"
     *
     * Generated from protobuf field <code>string period = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPeriod($var)
    {
        GPBUtil::checkString($var, True);
        $this->period = $var;

        return $this;
    }

}

