<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/transaction.proto

namespace Transaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transaction.GetBudgetsRequest</code>
 */
class GetBudgetsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * format: "YYYY-MM"
     *
     * Generated from protobuf field <code>string period = 1;</code>
     */
    protected $period = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $period
     *           format: "YYYY-MM"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * format: "YYYY-MM"
     *
     * Generated from protobuf field <code>string period = 1;</code>
     * @return string
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * format: "YYYY-MM"
     *
     * Generated from protobuf field <code>string period = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPeriod($var)
    {
        GPBUtil::checkString($var, True);
        $this->period = $var;

        return $this;
    }

}

