<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/transaction.proto

namespace Transaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transaction.GetBudgetsResponse</code>
 */
class GetBudgetsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .transaction.Budget budgets = 1;</code>
     */
    private $budgets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Transaction\Budget>|\Google\Protobuf\Internal\RepeatedField $budgets
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.Budget budgets = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBudgets()
    {
        return $this->budgets;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.Budget budgets = 1;</code>
     * @param array<\Transaction\Budget>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBudgets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Transaction\Budget::class);
        $this->budgets = $arr;

        return $this;
    }

}

